config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'static_pages#top'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    } 
  
  # 管理者の新規作成とログイン
  devise_for :admin_users, controllers: {
    registrations: 'admin_users/registrations',
    sessions: 'admin_users/sessions'
  }
  
  devise_scope :user do
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end

  # 管理者のルーティングを簡素化
  devise_scope :admin_user do
    get "admin/signup", :to => "admin_users/registrations#new"
    get "admin/login", :to => "admin_users/sessions#new"
    get "admin/logout", :to => "admin_users/sessions#destroy"
  end

  resources :admin_users, only:[:show] do
    resources :users, only:[:index, :show] 

    resources :folders do

      member do
        get "randam"
      end

    end
     
    resources :questions

  end
  
  # 退会についてのeditとupdate的なアクション
  # asで好きなルーティングヘルパーに設定
  get "admin_users/:admin_user_id/users/:id/unsubscribe" => "users#unsubscribe", as: 'confirm_unsubscribe'
  patch "admin_users/:admin_user_id/users/:id/withdraw" => "users#withdraw", as: 'withdraw_user'



  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
    @admin_user = AdminUser.find(1)
    @folders = @admin_user.folders
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/top.html.erb
<!-- deviseを複数のscopeで使う練習、activestorageでの写真投稿-->
<!-- 管理者→従業員のアカ作成, フォルダ作成, 問題作成 -->
<!-- 従業員→問題作成 -->
<!-- 従業員退会 -->

<div class="intro">
 <div class="row">
  <div class="col-md-6 offset-3">
    <p>チャートの基本例題をランダムで演習することができます。</p><br>
    <p>数IA: 数と式、集合と命題、2次関数、図形と計量、データと分析、<br>場合の数と確率、整数の性質、図形の性質</p>
    <p>数IIB: 図形と方程式、三角関数、指数・対数関数、微分、積分、<br>数列、ベクトル</p>

    <div class="post-btn-area">
      <% if admin_user_signed_in? %>
        <%= link_to "問題作成", new_admin_user_question_path(current_admin_user), class:"btn btn-danger" %><br>
      <% elsif user_signed_in? %>
        <%= link_to "問題作成", new_admin_user_question_path(current_user.admin_user.id), class:"btn btn-danger" %><br>
      <% end %>

    <div class="folder-index">
      <% if admin_user_signed_in? %>
        <%= link_to "フォルダ一覧", admin_user_folders_path(current_admin_user), class:"btn btn-warning" %>
      <% elsif user_signed_in? %>
        <%= link_to "フォルダ一覧", admin_user_folders_path(current_user.admin_user.id), class:"btn btn-warning" %>
      <% end %>
    </div>

    <div class="test-link">
      <% @folders.each do |folder| %>
        <!-- 現段階では、生徒にはログインさせないので、1人の管理者（id=1）のフォルダにアクセスできれば十分　-->
        <%= link_to folder.name, randam_admin_user_folder_path(@admin_user.id, folder.id) %>
      <% end %>
    </div>

    <div class="login-area" >
      <%= link_to "スタッフログイン", login_path %>
      <%= link_to "管理者ログイン", admin_login_path %>
    </div>

  </div>
 </div>
</div>