config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'static_pages#top'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    } 
  
  # 管理者の新規作成とログイン
  devise_for :admin_users, controllers: {
    registrations: 'admin_users/registrations',
    sessions: 'admin_users/sessions'
  }
  
  devise_scope :user do
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end

  # 管理者のルーティングを簡素化
  devise_scope :admin_user do
    get "admin/signup", :to => "admin_users/registrations#new"
    get "admin/login", :to => "admin_users/sessions#new"
    get "admin/logout", :to => "admin_users/sessions#destroy"
  end

  resources :admin_users, only:[:show] do
    resources :users, only:[:index, :show] 

    resources :folders do

      member do
        get "randam"
      end

    end
     
    resources :questions

  end
  
  # 退会についてのeditとupdate的なアクション
  # asで好きなルーティングヘルパーに設定
  get "admin_users/:admin_user_id/users/:id/unsubscribe" => "users#unsubscribe", as: 'confirm_unsubscribe'
  patch "admin_users/:admin_user_id/users/:id/withdraw" => "users#withdraw", as: 'withdraw_user'



  
end

app/models/folder.rb
class Folder < ApplicationRecord
  belongs_to :admin_user
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  include SessionsHelper
  # 正しい管理者→CUD
  # 正しい管理者or親が正しい管理者であるスタッフ→R

  before_action :login_admin_user_or_login_user, only:[:new,:create, :index, :show] 
  before_action :set_admin_user
  before_action :correct_admin_user, only:[:new, :create] 
  before_action :correct_admin_user_or_user_of_correct_admin_user, only:[:index, :show]
  before_action :set_folder, only:[:show, :randam]

  def new
    @folder = @admin_user.folders.build
  end

  def create
    @folder = @admin_user.folders.build(folder_params)
    if @folder.save
      flash[:success]="フォルダーを作成しました"
      redirect_to admin_user_folders_url(@admin_user)
    else
      render :new
    end
  end

  def index
    @folders = @admin_user.folders
  end

  def show
    @questions = @admin_user.questions.where(folder_in: @folder.name)
  end
  
  # テストページ。非ログインでも閲覧可能
  def randam
    @questions = @admin_user.questions.where(folder_in: @folder.name )
    
    @chapter1_questions=@questions.where(chapter: 1) 
    @chapter1_question_selected = @chapter1_questions.offset( rand( @chapter1_questions.count ) ).first

    @chapter2_questions=@questions.where(chapter:2)
    @chapter2_question_selected = @chapter2_questions.offset( rand( @chapter2_questions.count ) ).first
    
    @chapter3_questions=@questions.where(chapter:3)
    @chapter3_question_selected = @chapter3_questions.offset( rand( @chapter3_questions.count ) ).first
    
    @chapter4_questions=@questions.where(chapter:4)
    @chapter4_question_selected = @chapter4_questions.offset( rand( @chapter4_questions.count ) ).first
    
    @chapter5_questions=@questions.where(chapter: 5) 
    @chapter5_question_selected = @chapter5_questions.offset( rand( @chapter5_questions.count ) ).first

    @chapter6_questions=@questions.where(chapter:6)
    @chapter6_question_selected = @chapter6_questions.offset( rand( @chapter6_questions.count ) ).first
    
    @chapter7_questions=@questions.where(chapter:7)
    @chapter7_question_selected = @chapter7_questions.offset( rand( @chapter7_questions.count ) ).first
    
    @chapter8_questions=@questions.where(chapter:8)
    @chapter8_question_selected = @chapter8_questions.offset( rand( @chapter8_questions.count ) ).first
    
  end


  private
    def folder_params
      params.require(:folder).permit(:name, :admin_user_id , {:user_ids => []})
    end

    def login_admin_user_or_login_user
      unless admin_user_signed_in? || user_signed_in?
        flash[:alert]="管理者か従業員でログインしてください"
        redirect_to root_url
      end
    end

    def set_admin_user
      @admin_user = AdminUser.find(params[:admin_user_id])
    end

    def correct_admin_user
      unless current_admin_user?(@admin_user)
        flash[:alert]="権限がありません"
        redirect_to root_url
      end
    end

    def correct_admin_user_or_user_of_correct_admin_user
      if admin_user_signed_in?
        unless current_admin_user?(@admin_user)
          flash[:alert]="権限がありません"
          redirect_to root_url
        end
      elsif user_signed_in?
        unless @admin_user == current_user.admin_user
          flash[:alert]="権限がありません"
          redirect_to root_url
        end
      end
    end

    def set_folder
      @folder = @admin_user.folders.find(params[:id])
    end

      
    
    
  end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/index.html.erb
<% @folders.each do |folder| %>
  <%= link_to folder.name, admin_user_folder_path(@admin_user, folder) %><br>
<% end %>

<%
=begin%>
 <%= link_to "フォルダ作成", new_admin_user_folder_path(current_admin_user), class:"btn btn-light" %><br> 
<%
=end%>
      

app/views/folders/new.html.erb
<h1>フォルダを作成（テキストの登録）</h1>
<%= form_with(model:@folder, url:admin_user_folders_path(@admin_user) ,local: true) do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>

  <% if admin_user_signed_in? %>
    <%= f.hidden_field :admin_user_id , :value => current_admin_user.id %> 
  <% elsif user_signed_in? %>
    <%= f.hidden_field :admin_user_id , :value => current_user.admin_user.id %> 
  <% end %>

  <%= f.submit :"新規作成" %>

<% end %>

app/views/folders/randam.html.erb
<%= @folder.name %><br>
<%= link_to "問題をリセット", "#", class:"btn btn-danger" %>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  <!--カルーセルの枠にidを付与し、画像のidと紐付け。data-interval="3000"はなしにした-->
  <div id="carousel" class="carousel slide" data-ride="carousel" >
    <ol class="carousel-indicators">
      <li data-target="#carousel" data-slide-to="0" class="active"></li>
      <li data-target="#carousel" data-slide-to="1"></li>
      <li data-target="#carousel" data-slide-to="2"></li>
      <li data-target="#carousel" data-slide-to="3"></li>
      <li data-target="#carousel" data-slide-to="4"></li>
      <li data-target="#carousel" data-slide-to="5"></li>
      <li data-target="#carousel" data-slide-to="6"></li>
      <li data-target="#carousel" data-slide-to="7"></li>
    </ol>
    <div class="carousel-inner">
      <!--「activeクラス」が付与されることで、画像が表示される-->
      <div class="carousel-item active">
        <!--w-50は「幅を50％に指定」と言う意味です。srcで画像を指定します。-->
        <% if @chapter1_question_selected.image.attached? %>
          <%= image_tag @chapter1_question_selected.image, class:"d-block w-100" %>
        <% else %>
          <%= image_tag '/default.png' %>
        <% end %>
      </div>
     
      <div class="carousel-item">
        <% if @chapter2_question_selected.image.attached? %> 
          <%= image_tag @chapter2_question_selected.image, class:"d-block w-100" %>
        <% end %>
      </div>
      <div class="carousel-item">
        <% if @chapter3_question_selected.image.attached? %>
          <%= image_tag @chapter3_question_selected.image, class:"d-block w-100"%>
        <% end %>
      </div>
      <div class="carousel-item">
        <% if @chapter4_question_selected.image.attached? %>
          <%= image_tag @chapter4_question_selected.image, class:"d-block w-100" %>
        <% end %>
      </div>
      <div class="carousel-item">
        <% if @chapter5_question_selected.image.attached? %>
          <%= image_tag @chapter5_question_selected.image, class:"d-block w-100" %>
        <% end %>
      </div>
      <div class="carousel-item">
        <% if @chapter6_question_selected.image.attached? %>
          <%= image_tag @chapter6_question_selected.image, class:"d-block w-100" %>
        <% end %>
      </div>
      <div class="carousel-item">
        <% if @chapter7_question_selected.image.attached? %>
          <%= image_tag @chapter7_question_selected.image, class:"d-block w-100" %>
        <% end %>
      </div>
      <div class="carousel-item">
        <% if @chapter8_question_selected.image.attached? %>
          <%= image_tag @chapter8_question_selected.image, class:"d-block w-100" %>
        <% end %>
      </div>
    </div>
  </div>
  
  <!-- コントロールボタン -->
  <div class="control-buttons mt-1">
    <input type="button" class="btn btn-outline-primary prev-slide" value="＜">
    <input type="button" class="btn btn-outline-primary next-slide" value="＞">
  </div>  
  
  <script type="text/javascript">
  
  // 前の画像へ
  $(".prev-slide").on('click',function(){
    $("#carousel").carousel('prev');
  });
  // 次の画像へ
  $(".next-slide").on('click',function(){
    $("#carousel").carousel('next');
  });
  </script>

  <style>
  /*インジケーターの位置調整*/
  .carousel-indicators{
  margin-right: 20%;
  background-color:green;
  }
  /*「次へ」「前へ」ボタンの位置調整*/
  .mt-1{
  margin-left:520px;
  } 
  </style>

app/views/folders/show.html.erb
<h1>このフォルダの問題一覧</h1>
<% @questions.each do |question| %>
  <% if question.image.attached? %>
    <%= image_tag question.image, class:"d-block w-100" %>
    <% if question.user.present? %>
      <%= question.user.name %>
    <% end %>
    <% if admin_user_signed_in? %>
      <%=link_to "削除", admin_user_question_path(@admin_user, question), method: :delete %><br>
    <% end %>
   <% end %>
<% end %>